version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      - PGDATA=/data
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - blogging-plattform_db:/data
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  blogging-plattform_db:
